spring.application.name=ManageRooms
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/ManageRoomsDB
spring.datasource.username=Receptionist
spring.datasource.password=SecretPassword
